# Generated by Django 5.1.1 on 2024-11-11 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_marca_remove_device_marca_device_marcas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Processor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tipo')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de Edición')),
            ],
            options={
                'verbose_name': 'procesador',
                'verbose_name_plural': 'procesadores',
                'ordering': ['-created'],
            },
        ),
        migrations.RemoveField(
            model_name='device',
            name='procesador',
        ),
        migrations.AlterField(
            model_name='device',
            name='marcas',
            field=models.ManyToManyField(to='devices.marca', verbose_name='Marcas'),
        ),
        migrations.AddField(
            model_name='device',
            name='processors',
            field=models.ManyToManyField(to='devices.processor', verbose_name='Procesador'),
        ),
    ]
