# Generated by Django 5.1.1 on 2024-11-13 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0006_device_serie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tipo')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de Edición')),
            ],
            options={
                'verbose_name': 'ram',
                'verbose_name_plural': 'rams',
                'ordering': ['-created'],
            },
        ),
        migrations.AddField(
            model_name='device',
            name='rams',
            field=models.ManyToManyField(to='devices.ram', verbose_name='RAM'),
        ),
    ]
