# Generated by Django 5.1.1 on 2024-11-13 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0007_ram_device_rams'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Capacidad')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de Edición')),
            ],
            options={
                'verbose_name': 'disco',
                'verbose_name_plural': 'discos',
                'ordering': ['-created'],
            },
        ),
        migrations.AlterField(
            model_name='ram',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Capacidad'),
        ),
        migrations.AddField(
            model_name='device',
            name='discos',
            field=models.ManyToManyField(to='devices.disco', verbose_name='Disco Duro'),
        ),
    ]
