# Generated by Django 5.1.1 on 2024-11-25 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0011_mouse_device_mouses'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audifono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, verbose_name='Código Audífono')),
                ('name', models.CharField(max_length=100, verbose_name='Marca Áudífono')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de Edición')),
            ],
            options={
                'verbose_name': 'audifono',
                'verbose_name_plural': 'audifonos',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, verbose_name='Código Cámara')),
                ('name', models.CharField(max_length=100, verbose_name='Marca Cámara')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de Edición')),
            ],
            options={
                'verbose_name': 'camara',
                'verbose_name_plural': 'camaras',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Cooler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, verbose_name='Código Cooler')),
                ('name', models.CharField(max_length=100, verbose_name='Marca Cooler')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de Edición')),
            ],
            options={
                'verbose_name': 'cooler',
                'verbose_name_plural': 'coolers',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Keyboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, verbose_name='Código Teclado')),
                ('name', models.CharField(max_length=100, verbose_name='Marca Teclado')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de Edición')),
            ],
            options={
                'verbose_name': 'teclado',
                'verbose_name_plural': 'teclados',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, verbose_name='Código Monitor')),
                ('name', models.CharField(max_length=100, verbose_name='Marca Monitor')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de Edición')),
            ],
            options={
                'verbose_name': 'monitor',
                'verbose_name_plural': 'monitores',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Stabilizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, verbose_name='Código Estabilizador')),
                ('name', models.CharField(max_length=100, verbose_name='Marca Estabilizador')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de Edición')),
            ],
            options={
                'verbose_name': 'estabilizador',
                'verbose_name_plural': 'estabilizadores',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Supresor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, verbose_name='Código Supresor')),
                ('name', models.CharField(max_length=100, verbose_name='Marca Supresor')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de Edición')),
            ],
            options={
                'verbose_name': 'supresor',
                'verbose_name_plural': 'supresores',
                'ordering': ['-created'],
            },
        ),
        migrations.AddField(
            model_name='device',
            name='audifonos',
            field=models.ManyToManyField(to='devices.audifono', verbose_name='Audifono'),
        ),
        migrations.AddField(
            model_name='device',
            name='camaras',
            field=models.ManyToManyField(to='devices.camera', verbose_name='Camara'),
        ),
        migrations.AddField(
            model_name='device',
            name='cooler',
            field=models.ManyToManyField(to='devices.cooler', verbose_name='Cooler'),
        ),
        migrations.AddField(
            model_name='device',
            name='teclados',
            field=models.ManyToManyField(to='devices.keyboard', verbose_name='Teclado'),
        ),
        migrations.AddField(
            model_name='device',
            name='monitores',
            field=models.ManyToManyField(to='devices.monitor', verbose_name='Monitor'),
        ),
        migrations.AddField(
            model_name='device',
            name='estabilizadores',
            field=models.ManyToManyField(to='devices.stabilizer', verbose_name='Estabilizador'),
        ),
        migrations.AddField(
            model_name='device',
            name='supresores',
            field=models.ManyToManyField(to='devices.supresor', verbose_name='Supresor de Pico'),
        ),
    ]
