# Generated by Django 5.1.1 on 2024-11-26 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0014_alter_device_content_alter_device_modelo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='mouses',
            field=models.ManyToManyField(blank=True, null=True, to='devices.mouse', verbose_name='Mouse'),
        ),
    ]
