# Generated by Django 5.1.1 on 2024-11-28 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0018_remove_worker_cargo_worker_puesto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='puestos',
        ),
    ]
