# Generated by Django 5.1.1 on 2024-11-06 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('area', models.CharField(max_length=50, verbose_name='Área')),
                ('cargo', models.CharField(max_length=50, verbose_name='Cargo')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de Edición')),
            ],
            options={
                'verbose_name': 'Trabajador',
                'verbose_name_plural': 'Trabajadores',
                'ordering': ['-created'],
            },
        ),
        migrations.AddField(
            model_name='device',
            name='workers',
            field=models.ManyToManyField(to='devices.worker', verbose_name='Trabajadores'),
        ),
    ]
