# Generated by Django 5.1.1 on 2024-11-11 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_worker_device_workers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de Edición')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.AddField(
            model_name='device',
            name='areas',
            field=models.ManyToManyField(to='devices.area', verbose_name='Areas'),
        ),
    ]
