# Generated by Django 5.1.1 on 2024-11-13 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0008_disco_alter_ram_name_device_discos'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='tarjetaVideo',
            field=models.CharField(default='some string', max_length=200, verbose_name='Tarjeta de Video'),
        ),
    ]
