# Generated by Django 5.1.1 on 2024-11-18 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0009_device_tarjetavideo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warranty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='Garantía')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de Edición')),
            ],
            options={
                'verbose_name': 'garantia',
                'verbose_name_plural': 'garantias',
                'ordering': ['-created'],
            },
        ),
        migrations.AlterField(
            model_name='device',
            name='content',
            field=models.TextField(verbose_name='Observaciones'),
        ),
        migrations.AddField(
            model_name='device',
            name='warrantys',
            field=models.ManyToManyField(to='devices.warranty', verbose_name='Grantía'),
        ),
    ]
