# Generated by Django 5.1.1 on 2024-11-18 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0010_warranty_alter_device_content_device_warrantys'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, verbose_name='Código Mouse')),
                ('name', models.CharField(max_length=100, verbose_name='Marca Mouse')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de Edición')),
            ],
            options={
                'verbose_name': 'mouse',
                'verbose_name_plural': 'mouses',
                'ordering': ['-created'],
            },
        ),
        migrations.AddField(
            model_name='device',
            name='mouses',
            field=models.ManyToManyField(to='devices.mouse', verbose_name='Mouse'),
        ),
    ]
