# Generated by Django 5.1.1 on 2024-11-26 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0016_remove_worker_area_alter_worker_name_worker_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='Puesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de Edición')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.AddField(
            model_name='area',
            name='puestos',
            field=models.ManyToManyField(to='devices.puesto', verbose_name='Puesto'),
        ),
    ]
