# Generated by Django 5.1.1 on 2024-11-26 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0017_puesto_area_puestos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='cargo',
        ),
        migrations.AddField(
            model_name='worker',
            name='puesto',
            field=models.ManyToManyField(to='devices.puesto', verbose_name='Puestos'),
        ),
    ]
