# Generated by Django 5.1.4 on 2025-02-18 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0019_remove_area_puestos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marca',
            options={'ordering': ['-created'], 'verbose_name_plural': 'marcas'},
        ),
        migrations.AddField(
            model_name='worker',
            name='active',
            field=models.CharField(default='SI', max_length=20, verbose_name='Activo'),
        ),
    ]
