# Generated by Django 5.1.1 on 2024-10-16 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryComputer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de Edición')),
            ],
            options={
                'verbose_name': 'Computadora',
                'verbose_name_plural': 'Computadoras',
                'ordering': ['-created'],
            },
        ),
        migrations.AddField(
            model_name='computer',
            name='workers',
            field=models.ManyToManyField(to='computers.worker', verbose_name='Trabajadores'),
        ),
        migrations.AddField(
            model_name='computer',
            name='categoriesComputer',
            field=models.ManyToManyField(to='computers.categorycomputer', verbose_name='Categorías'),
        ),
    ]
