# Generated by Django 5.1.1 on 2024-10-24 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('computers', '0002_categorycomputer_computer_workers_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorycomputer',
            options={'ordering': ['-created'], 'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
    ]
