# Generated by Django 5.1.1 on 2024-10-30 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyboards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
